language: node_js
node_js:
    - "9"
dist: trusty
sudo: false

branches:
    only:
        - master

cache:
    directories:
        - node_modules

script:
    - npm run lint
    - npm run build --prod --base-href https://ben-barbier.github.io/formation-20181114-unicorn-ng/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/unicorn-ng
    on:
        branch: master
